function makeCard(
  id,
  category,
  title,
  titleZh,
  summary,
  summaryZh,
  prompt,
  promptZh,
  tools,
  page,
  keywords
) {
  return {
    id,
    category,
    title,
    titleZh,
    summary,
    summaryZh,
    prompt,
    promptZh,
    tools,
    page,
    keywords,
  };
}

function makeTip(
  id,
  category,
  title,
  titleZh,
  summary,
  summaryZh,
  prompt,
  promptZh,
  tools,
  page,
  keywords
) {
  return {
    id,
    category,
    title,
    titleZh,
    summary,
    summaryZh,
    prompt,
    promptZh,
    tools,
    page,
    keywords,
  };
}

const promptAtlasData = {
  categories: [
    {
      id: "fundamentals",
      name: "Prompt Foundations",
      nameZh: "提示詞基礎",
      summary:
        "Core practices for writing better prompts in Workspace-style assistants.",
      summaryZh: "適用於 Workspace 類 AI 助手的核心提示詞寫法。",
    },
    {
      id: "admin",
      name: "Administrative Support",
      nameZh: "行政支援",
      summary: "Agenda planning, inbox triage, travel support, and coordination.",
      summaryZh: "議程安排、郵件整理、差旅協調與行政統籌。",
    },
    {
      id: "communications",
      name: "Communications",
      nameZh: "企業傳訊",
      summary: "Press, internal messaging, executive narratives, and spokespeople prep.",
      summaryZh: "新聞稿、內部溝通、高層信息與發言人準備。",
    },
    {
      id: "customer-service",
      name: "Customer Service",
      nameZh: "客戶服務",
      summary: "Response drafting, issue resolution, feedback analysis, and self-service.",
      summaryZh: "回覆起草、複雜問題處理、回饋分析與自助支援。",
    },
    {
      id: "executives",
      name: "Executives",
      nameZh: "管理層",
      summary: "Mobile communication, briefings, research, and sharper decision support.",
      summaryZh: "流動溝通、簡報整理、研究摘要與決策支援。",
    },
    {
      id: "frontline",
      name: "Frontline Management",
      nameZh: "前線管理",
      summary: "Fast lookup, task flow, inventory visibility, and audit support.",
      summaryZh: "快速查找、任務流程、庫存掌握與稽核支援。",
    },
    {
      id: "hr",
      name: "Human Resources",
      nameZh: "人力資源",
      summary: "Hiring, onboarding, survey design, and employee communications.",
      summaryZh: "招聘、入職、員工調查與人事溝通。",
    },
    {
      id: "marketing",
      name: "Marketing",
      nameZh: "市場營銷",
      summary: "Brand strategy, campaigns, audience research, and content generation.",
      summaryZh: "品牌策略、活動策劃、受眾研究與內容生成。",
    },
    {
      id: "pm",
      name: "Project Management",
      nameZh: "項目管理",
      summary: "Status reporting, testing, retrospectives, and workback planning.",
      summaryZh: "狀態報告、測試規劃、回顧總結與倒排時程。",
    },
    {
      id: "sales",
      name: "Sales",
      nameZh: "銷售",
      summary: "Account research, proposals, calls, and relationship building.",
      summaryZh: "客戶研究、提案流程、通話準備與關係建立。",
    },
    {
      id: "small-business",
      name: "Small Business",
      nameZh: "小型企業",
      summary: "Pricing, productivity, lightweight marketing, and vendor coordination.",
      summaryZh: "價格比較、個人生產力、輕量營銷與供應商協調。",
    },
    {
      id: "startup",
      name: "Startup Leaders",
      nameZh: "創業領導者",
      summary: "Strategy shaping, fundraising stories, launch planning, and roadmap thinking.",
      summaryZh: "策略構思、募資敘事、產品上市與路線圖思考。",
    },
  ],
  tips: [
    makeTip(
      "tip-persona",
      "fundamentals",
      "Set a Persona",
      "先設定角色",
      "Tell the assistant who it should act like before asking for work.",
      "先告訴 AI 應以甚麼角色思考，再提出任務要求。",
      "Act as an operations lead supporting a regional team. Draft a concise update for stakeholders.",
      "請以區域營運主管身份思考，為持份者起草一份精簡更新。",
      ["Docs", "Gmail"],
      2,
      ["persona", "role", "task"]
    ),
    makeTip(
      "tip-context",
      "fundamentals",
      "Add Context",
      "加入背景",
      "Include audience, timing, source documents, and constraints.",
      "加入受眾、時間、來源文件與限制條件，輸出會更貼近需要。",
      "Using the Q2 review deck and meeting notes, summarize the top three risks for the VP audience.",
      "根據 Q2 回顧簡報與會議筆記，為 VP 受眾整理三個主要風險。",
      ["Docs", "Drive", "Gemini"],
      2,
      ["context", "constraints", "documents"]
    ),
    makeTip(
      "tip-format",
      "fundamentals",
      "Request a Format",
      "指定輸出格式",
      "Ask for bullets, tables, summaries, timelines, or email-ready copy.",
      "直接指定要子彈點、表格、摘要、時間線或可直接寄出的文案。",
      "Convert the meeting recap into a two-column table with owner and next step.",
      "把會議總結改寫成兩欄表格，包含負責人與下一步。",
      ["Docs", "Sheets"],
      2,
      ["format", "table", "bullets"]
    ),
    makeTip(
      "tip-iterate",
      "fundamentals",
      "Iterate Fast",
      "快速迭代",
      "Treat prompting like conversation: refine tone, depth, and structure.",
      "把提示詞當成對話，不斷微調語氣、深度與結構。",
      "Make this sharper for executives, then rewrite it in a warmer tone for managers.",
      "先把內容改得更適合高層閱讀，再重寫成較溫暖的管理層語氣。",
      ["Gemini", "Gmail"],
      3,
      ["iterate", "refine", "tone"]
    ),
  ],
  cards: [
    makeCard(
      "admin-agenda",
      "admin",
      "Plan a multi-day offsite agenda",
      "規劃多日團隊聚會議程",
      "Build a balanced agenda with strategy blocks, team bonding, and logistical pacing.",
      "建立兼顧策略討論、團隊互動與節奏安排的多日議程。",
      "You are supporting a newly formed cross-functional team. Draft a three-day offsite agenda with strategic workshops, informal bonding, and clear session goals for each day.",
      "你正在支援一個新成立的跨職能團隊。請起草一份三日 offsite 議程，包含策略工作坊、非正式團隊交流，以及每天清晰的會議目標。",
      ["Gemini", "Docs"],
      7,
      ["agenda", "offsite", "meeting", "strategy"]
    ),
    makeCard(
      "admin-inbox",
      "admin",
      "Triage a busy executive inbox",
      "整理高層繁忙郵箱",
      "Summarize priority messages, deadlines, and follow-ups after travel or leave.",
      "在出差或休假後，快速整理優先郵件、截止日期與待跟進事項。",
      "Review this recent email activity and produce a priority inbox summary with urgent threads, action items, and draft reply suggestions.",
      "請整理近期郵件活動，輸出一份優先郵箱摘要，列出緊急郵件串、行動項目，以及可直接使用的回覆建議。",
      ["Gmail"],
      8,
      ["email", "inbox", "triage", "follow-up"]
    ),
    makeCard(
      "admin-travel",
      "admin",
      "Coordinate business travel plans",
      "協調商務差旅安排",
      "Turn meeting goals and timing constraints into a clean travel itinerary.",
      "把會議目標與時間限制整理成清晰的差旅行程。",
      "Create a business travel plan for a two-day client trip including meeting windows, transit buffers, meal suggestions, and a concise itinerary table.",
      "請為兩日客戶出差建立商務行程，包含會議時段、交通緩衝、用餐建議，以及精簡的行程表。",
      ["Docs", "Sheets"],
      9,
      ["travel", "itinerary", "logistics", "table"]
    ),
    makeCard(
      "admin-expense",
      "admin",
      "Track travel and entertainment budgets",
      "追蹤差旅與招待預算",
      "Turn scattered receipts and policy rules into a budget-friendly spend summary.",
      "把零散收據與政策規則整理成清晰的差旅開支摘要。",
      "Organize these travel and entertainment expenses into a tracker that flags policy exceptions, reimbursement gaps, and budget impact by trip or person.",
      "請把這些差旅與招待支出整理成追蹤表，標示政策例外、報銷缺口，以及每次行程或每位同事對預算的影響。",
      ["Sheets", "Docs"],
      9,
      ["expense", "budget", "reimbursement", "policy"]
    ),
    makeCard(
      "communications-press",
      "communications",
      "Draft a press release",
      "起草新聞稿",
      "Shape a clear announcement with headline, quote, boilerplate, and media angle.",
      "以清楚結構撰寫公告，包含標題、引言、公司簡介與媒體角度。",
      "Draft a press release announcing our new service launch. Include a strong headline, customer value, executive quote, and a crisp closing boilerplate.",
      "請起草一份宣布新服務推出的新聞稿，包含有力標題、客戶價值、管理層引言，以及精簡的公司 boilerplate。",
      ["Docs"],
      10,
      ["press release", "announcement", "launch", "media"]
    ),
    makeCard(
      "communications-briefing",
      "communications",
      "Prepare an analyst briefing pack",
      "準備分析師簡報素材",
      "Turn long source material into briefing notes, key messages, and likely questions.",
      "把長篇資料整理成簡報重點、核心訊息與可能被問到的問題。",
      "Summarize the product update, market context, and financial highlights into a briefing pack with key talking points and anticipated analyst questions.",
      "請把產品更新、市場背景與財務亮點整理成分析師簡報素材，包含重點說法與預期問題。",
      ["Docs", "Drive"],
      11,
      ["analyst", "briefing", "talking points", "questions"]
    ),
    makeCard(
      "communications-spokesperson",
      "communications",
      "Create mock media interview questions",
      "設計模擬媒體訪問問題",
      "Stress-test a spokesperson with likely tough questions and clean response pivots.",
      "用可能的尖銳問題與轉向答法，提前訓練發言人。",
      "Generate a mock media interview for our spokesperson with easy, moderate, and difficult questions, followed by concise bridging points for each answer.",
      "請為我們的發言人設計一套模擬媒體訪問，包含容易、中等與困難問題，並為每題附上精簡的答題轉向點。",
      ["Docs", "Gemini"],
      12,
      ["interview", "media training", "spokesperson", "questions"]
    ),
    makeCard(
      "communications-internal",
      "communications",
      "Craft an internal leadership message",
      "撰寫內部領導層訊息",
      "Translate sensitive updates into calm, transparent communication for employees.",
      "把敏感更新轉化成冷靜、透明、適合員工閱讀的內部溝通。",
      "Draft an internal note from leadership explaining the upcoming organizational change, the reason behind it, what employees should expect next, and where to ask questions.",
      "請以領導層名義撰寫一封內部訊息，說明即將發生的組織變動、背後原因、員工接下來會遇到甚麼，以及可向哪裡提問。",
      ["Docs", "Gmail"],
      12,
      ["internal comms", "leadership", "change", "employee"]
    ),
    makeCard(
      "service-customer-comms",
      "customer-service",
      "Draft empathetic customer responses",
      "起草具同理心的客戶回覆",
      "Build replies that acknowledge frustration while moving the issue toward resolution.",
      "撰寫既能體諒客戶情緒，又能推進問題解決的回覆。",
      "Write a customer response that acknowledges the issue, explains the next step clearly, and offers a realistic resolution timeline in a calm, supportive tone.",
      "請撰寫一封客戶回覆，先同理問題，再清楚說明下一步，並以冷靜支持的語氣提供合理的解決時間表。",
      ["Gmail", "Docs"],
      13,
      ["support", "response", "empathy", "timeline"]
    ),
    makeCard(
      "service-faq",
      "customer-service",
      "Answer complex issues from FAQ material",
      "利用 FAQ 資料回答複雜問題",
      "Synthesize several knowledge sources into one structured answer for the customer.",
      "把多份知識來源整合成一個清晰、完整的客戶答覆。",
      "Using the FAQ, policy notes, and support history, create one clear response that answers all parts of the customer's question and flags any information that still needs confirmation.",
      "請根據 FAQ、政策說明與支援紀錄，整合成一份完整回覆，回答客戶所有問題，並標示仍需確認的資訊。",
      ["Docs", "Drive", "Gmail"],
      14,
      ["faq", "knowledge base", "complex issue", "support"]
    ),
    makeCard(
      "service-framework",
      "customer-service",
      "Standardize communication frameworks",
      "標準化客服溝通框架",
      "Turn support guidance into reusable response structures for the whole team.",
      "把客服指引整理成團隊可重複使用的回覆框架。",
      "Create a reusable customer response framework for billing, delivery, and product issues, including opening empathy lines, solution steps, and escalation language.",
      "請建立一套可重複使用的客戶回覆框架，涵蓋帳單、配送與產品問題，包含開場同理句、解決步驟與升級處理語句。",
      ["Docs"],
      14,
      ["framework", "template", "customer care", "standard"]
    ),
    makeCard(
      "service-feedback",
      "customer-service",
      "Analyze customer feedback themes",
      "分析客戶回饋主題",
      "Cluster comments into recurring complaints, wins, and product opportunities.",
      "把回饋聚類成常見投訴、亮點與產品改善機會。",
      "Review this batch of customer feedback and group it into recurring themes, sentiment signals, urgent product issues, and suggested action owners.",
      "請分析這批客戶回饋，整理成重複主題、情緒訊號、緊急產品問題，以及建議跟進負責人。",
      ["Sheets", "Docs"],
      15,
      ["feedback", "sentiment", "themes", "analysis"]
    ),
    makeCard(
      "service-self-service",
      "customer-service",
      "Enable customer self-service",
      "建立客戶自助支援內容",
      "Convert repeated support questions into concise help-center style instructions.",
      "把重複出現的支援問題轉成精簡的說明中心內容。",
      "Turn these repeated support cases into a self-service help article with step-by-step instructions, common mistakes, and when to contact an agent.",
      "請把這些重複出現的支援案例整理成自助說明文章，包含步驟指引、常見錯誤，以及何時需要聯絡客服。",
      ["Docs"],
      16,
      ["self-service", "help center", "knowledge article", "support"]
    ),
    makeCard(
      "service-voc",
      "customer-service",
      "Run voice-of-customer research",
      "進行客戶心聲研究",
      "Translate surveys and interview notes into product and service signals.",
      "把問卷與訪談筆記整理成產品與服務層面的訊號。",
      "Analyze these survey and interview responses to surface the strongest voice-of-customer themes, emotional drivers, unmet needs, and next research questions.",
      "請分析這些問卷與訪談回覆，找出最強烈的客戶心聲主題、情緒驅動因素、未被滿足的需求，以及下一步研究問題。",
      ["Sheets", "Docs"],
      16,
      ["voice of customer", "research", "survey", "insights"]
    ),
    makeCard(
      "executive-mobile",
      "executives",
      "Communicate on the go",
      "在流動情境下快速溝通",
      "Convert rough notes into polished responses while traveling or between meetings.",
      "在出差或趕會議途中，把零散想法快速整理成得體回覆。",
      "Turn these short voice-note style ideas into a concise executive email with a decisive tone, one clear ask, and three supporting points.",
      "請把這些語音筆記式的零散想法整理成一封精簡的高層電郵，語氣果斷，有一個明確請求與三個支持要點。",
      ["Gmail", "Docs"],
      17,
      ["mobile", "executive", "email", "voice notes"]
    ),
    makeCard(
      "executive-productivity",
      "executives",
      "Enhance personal productivity and time management",
      "提升個人生產力與時間管理",
      "Turn meetings, open work, and decisions into a sharper executive operating rhythm.",
      "把會議、待辦與決策整理成更清晰的高層工作節奏。",
      "Review my upcoming week and turn it into a focused executive plan with top priorities, delegate-able items, preparation windows, and recovery time.",
      "請檢視我接下來一週的安排，整理成一份高層工作計畫，包含最高優先事項、可委派項目、準備時段與休息空檔。",
      ["Calendar", "Docs", "Gemini"],
      18,
      ["productivity", "time management", "priorities", "planning"]
    ),
    makeCard(
      "executive-deck",
      "executives",
      "Build presentation outlines quickly",
      "快速建立簡報大綱",
      "Turn a topic, audience, and decision goal into a board-ready narrative arc.",
      "根據主題、受眾與決策目標，快速整理出適合高層的簡報脈絡。",
      "Create a presentation outline for senior leadership on this initiative. Include a compelling opening, current state, options, recommendation, and decision slide.",
      "請為高層建立此專案的簡報大綱，包含有力開場、現況、選項、建議方案與決策頁。",
      ["Slides", "Docs"],
      18,
      ["presentation", "outline", "leadership", "decision"]
    ),
    makeCard(
      "executive-hard-comms",
      "executives",
      "Prepare challenging employee communications",
      "準備艱難員工溝通",
      "Shape difficult messages with clarity, empathy, and realistic next steps.",
      "以清晰、同理與實際可行的下一步來處理艱難溝通。",
      "Draft a communication plan for a sensitive employee update, including the leadership message, manager talking points, likely questions, and the tone to maintain throughout.",
      "請為敏感員工更新設計一套溝通方案，包含領導層訊息、主管談話重點、可能問題，以及全程要維持的語氣。",
      ["Docs", "Gmail"],
      18,
      ["employee communication", "sensitive", "manager", "talking points"]
    ),
    makeCard(
      "executive-market-research",
      "executives",
      "Perform market research and campaign planning",
      "進行市場研究與活動規劃",
      "Convert open-ended market questions into a concise brief for action.",
      "把開放式市場問題整理成可執行的行動簡報。",
      "Summarize this market landscape and recommend the strongest campaign directions, assumptions to test, and signals that would change our plan.",
      "請整理這個市場格局，建議最值得投入的活動方向、需要驗證的假設，以及哪些訊號出現時要改變計畫。",
      ["Gemini", "Docs"],
      19,
      ["market research", "campaign", "strategy", "signals"]
    ),
    makeCard(
      "executive-thought-leadership",
      "executives",
      "Brainstorm thought leadership content",
      "發想思想領導內容",
      "Generate strong opinion-led angles without losing business relevance.",
      "生成有觀點的內容角度，同時保持商業相關性。",
      "Suggest five thought leadership angles our leadership team could publish on this quarter, with a distinct point of view, target audience, and preferred format for each.",
      "請提出五個本季適合由管理層發表的思想領導題目，每個包含鮮明觀點、目標受眾與最適合的內容形式。",
      ["Docs"],
      20,
      ["thought leadership", "content", "leadership", "angles"]
    ),
    makeCard(
      "executive-competitive",
      "executives",
      "Conduct competitive analysis",
      "進行競爭分析",
      "Summarize positioning gaps, competitor moves, and likely responses.",
      "整理定位差距、競爭對手動向與可能應對方式。",
      "Create a competitive analysis comparing our offer with the top alternatives, covering strengths, weaknesses, market messaging, and likely response strategies.",
      "請建立一份競爭分析，比較我們與主要替代方案的優劣、市場訊息與可能的應對策略。",
      ["Docs", "Sheets"],
      20,
      ["competitive analysis", "positioning", "market", "alternatives"]
    ),
    makeCard(
      "executive-trends",
      "executives",
      "Summarize technology or market trends",
      "整理科技或市場趨勢",
      "Compress broad research into executive takeaways, implications, and watchouts.",
      "把廣泛研究壓縮成高層可快速理解的重點、影響與風險提示。",
      "Summarize the latest market and technology developments for an executive audience. Focus on what matters now, what to monitor next, and possible business implications.",
      "請為高層整理最新市場與科技發展，重點說明當下重要事項、下一步要觀察的變化，以及可能的商業影響。",
      ["Gemini", "Docs"],
      21,
      ["trends", "market", "technology", "executive summary"]
    ),
    makeCard(
      "executive-explain-tech",
      "executives",
      "Explain technical topics to non-technical audiences",
      "向非技術受眾說明技術議題",
      "Translate complexity into plain-language business meaning.",
      "把複雜技術轉化成容易理解的商業語言。",
      "Explain this technical concept for a non-technical audience using plain language, one analogy, what it changes in practice, and why leaders should care.",
      "請用白話方式向非技術受眾說明這個技術概念，加入一個類比、實際影響，以及領導層為何需要關注。",
      ["Docs", "Slides"],
      21,
      ["technical explanation", "non-technical", "plain language", "analogy"]
    ),
    makeCard(
      "executive-vendor-research",
      "executives",
      "Research vendor products and features",
      "研究供應商產品與功能",
      "Turn long product pages into a decision-oriented vendor snapshot.",
      "把冗長的產品資訊整理成利於決策的供應商快照。",
      "Compare these vendor products by core features, implementation complexity, pricing signals, security considerations, and the questions we still need answered.",
      "請比較這些供應商產品的核心功能、導入複雜度、價格訊號、安全考量，以及我們仍需追問的問題。",
      ["Docs", "Sheets"],
      22,
      ["vendor", "features", "comparison", "security"]
    ),
    makeCard(
      "executive-tech-summary",
      "executives",
      "Develop technical summaries",
      "整理技術摘要",
      "Turn deep source material into a useful one-pager for leaders or partners.",
      "把深入技術內容整理成高層或合作夥伴可讀的一頁摘要。",
      "Create a one-page technical summary covering what changed, why it matters, implementation status, risks, and the decisions needed from leadership.",
      "請建立一頁式技術摘要，說明有甚麼改變、為何重要、目前實施狀態、風險，以及需要領導層做的決定。",
      ["Docs"],
      22,
      ["technical summary", "one pager", "risks", "decisions"]
    ),
    makeCard(
      "executive-assets",
      "executives",
      "Track IT assets",
      "追蹤 IT 資產",
      "Make asset data easier to review, update, and escalate.",
      "讓資產資料更容易檢視、更新與升級處理。",
      "Review this IT asset list and build a clean tracker that shows ownership, renewal timing, lifecycle status, and items that need immediate action.",
      "請檢視這份 IT 資產清單，建立一個清楚的追蹤表，顯示擁有人、續期時間、生命週期狀態，以及需要立即處理的項目。",
      ["Sheets"],
      22,
      ["IT assets", "tracker", "renewal", "lifecycle"]
    ),
    makeCard(
      "executive-appreciation",
      "executives",
      "Demonstrate employee appreciation",
      "表達員工欣賞與肯定",
      "Draft recognition messages that feel personal instead of generic.",
      "寫出更個人化、而非公式化的肯定訊息。",
      "Write three versions of an employee appreciation note: one for a public team message, one for a private message, and one for a leadership shout-out.",
      "請撰寫三個版本的員工表揚訊息：一個用於團隊公開訊息、一個私下訊息，以及一個供管理層公開表揚。",
      ["Docs", "Gmail"],
      22,
      ["appreciation", "recognition", "employee", "message"]
    ),
    makeCard(
      "executive-satisfaction",
      "executives",
      "Assess employee satisfaction",
      "評估員工滿意度",
      "Turn survey outputs into a focused readout for action.",
      "把員工調查輸出整理成可行動的重點報告。",
      "Summarize this employee satisfaction data into strengths, top concerns, likely root causes, and the first three actions leaders should take.",
      "請把這份員工滿意度數據整理成優勢、主要關注點、可能根因，以及領導層應優先採取的三個行動。",
      ["Sheets", "Docs"],
      23,
      ["employee satisfaction", "survey", "root cause", "actions"]
    ),
    makeCard(
      "frontline-lookup",
      "frontline",
      "Find accurate information quickly",
      "快速找到準確資訊",
      "Pull together policy or promotion details for fast customer-facing answers.",
      "快速彙整政策或促銷細節，幫前線人員即時回應客戶。",
      "Search the available product and policy information, then provide a short answer I can use with a customer, plus the source details I should double-check.",
      "請搜尋現有產品與政策資訊，提供一段我可直接對客使用的簡短答覆，並列出需要再次核對的來源重點。",
      ["Gemini", "Drive"],
      24,
      ["lookup", "policy", "customer answer", "accuracy"]
    ),
    makeCard(
      "frontline-collaboration",
      "frontline",
      "Improve team collaboration by finding the right files",
      "透過找對文件改善團隊協作",
      "Reduce time lost to searching for SOPs, shift notes, or store updates.",
      "減少尋找 SOP、交班筆記或門店更新所浪費的時間。",
      "Based on this request, identify which files or notes are most relevant, summarize them for the shift team, and list what still appears missing.",
      "請根據這個需求，找出最相關的文件或筆記，為輪班團隊整理摘要，並列出目前仍然欠缺的資訊。",
      ["Drive", "Docs"],
      25,
      ["collaboration", "files", "SOP", "shift notes"]
    ),
    makeCard(
      "frontline-tasks",
      "frontline",
      "Streamline daily task management",
      "精簡每日任務管理",
      "Organize open work into priorities, blockers, owners, and next actions.",
      "把待辦工作整理成優先級、阻礙、負責人與下一步。",
      "Turn this list of open store or shift tasks into a prioritized action tracker with urgency, owner, status, and recommended next step.",
      "請把這份門店或班次待辦清單整理成具優先順序的行動追蹤表，包含緊急程度、負責人、狀態與建議下一步。",
      ["Sheets"],
      25,
      ["tasks", "tracker", "priorities", "operations"]
    ),
    makeCard(
      "frontline-inventory",
      "frontline",
      "Check and explain inventory status",
      "檢視並說明庫存狀態",
      "Summarize stock levels, low-stock risk, and recommended actions for the floor team.",
      "總結庫存水平、缺貨風險與前線團隊應採取的行動。",
      "Review this inventory sheet and highlight low-stock items, reorder priorities, and any customer-facing risks we should communicate today.",
      "請分析這份庫存表，指出低庫存項目、補貨優先順序，以及今天需要對客說明的風險。",
      ["Sheets"],
      26,
      ["inventory", "stock", "reorder", "risk"]
    ),
    makeCard(
      "frontline-audits",
      "frontline",
      "Prepare for audits",
      "準備稽核",
      "Convert requirements into a checklist the team can actually use on the floor.",
      "把稽核要求轉成團隊在現場真的可使用的清單。",
      "Create an audit preparation checklist from these requirements, grouped by area, with pass-fail checks, evidence to gather, and common mistakes to avoid.",
      "請根據這些要求建立一份稽核準備清單，按區域分組，列出通過標準、需準備的證據，以及常見錯誤。",
      ["Docs", "Sheets"],
      26,
      ["audit", "checklist", "compliance", "evidence"]
    ),
    makeCard(
      "hr-welcome",
      "hr",
      "Welcome new employees",
      "歡迎新員工",
      "Create warm onboarding communication with timeline, contacts, and expectations.",
      "建立溫暖清晰的入職溝通，包含時間表、聯絡窗口與預期安排。",
      "Draft a welcome message for a new employee that covers their first-week schedule, who they will meet, what to prepare, and where to ask for help.",
      "請起草一封新員工歡迎訊息，說明首週安排、會見對象、需準備事項，以及遇到問題可向哪裡求助。",
      ["Docs", "Gmail"],
      27,
      ["welcome", "onboarding", "employee", "schedule"]
    ),
    makeCard(
      "hr-recruitment",
      "hr",
      "Report on recruitment metrics",
      "匯報招聘指標",
      "Turn hiring data into a readable summary of pipeline health and bottlenecks.",
      "把招聘數據整理成易讀摘要，呈現招聘漏斗健康度與瓶頸。",
      "Analyze our recruiting metrics and produce a short summary covering funnel conversion, time-to-fill, bottlenecks, and recommendations for the next month.",
      "請分析我們的招聘指標，整理成精簡摘要，涵蓋漏斗轉換率、招聘周期、主要瓶頸與下月建議。",
      ["Sheets", "Docs"],
      28,
      ["recruiting", "metrics", "pipeline", "hiring"]
    ),
    makeCard(
      "hr-recruiting-process",
      "hr",
      "Manage the recruiting process",
      "管理招聘流程",
      "Keep role intake, candidate stages, and communications aligned.",
      "讓職位需求、候選人階段與溝通節奏保持一致。",
      "Create a recruiting workflow for this role that covers intake, sourcing, screening, interviews, decision checkpoints, and candidate communication timing.",
      "請為這個職位建立招聘流程，涵蓋需求確認、搜尋、初篩、面試、決策節點，以及候選人溝通時點。",
      ["Docs", "Sheets"],
      28,
      ["recruiting process", "workflow", "candidate stages", "timing"]
    ),
    makeCard(
      "hr-interview",
      "hr",
      "Manage the interview process",
      "管理面試流程",
      "Generate structured interview kits, candidate communications, and follow-ups.",
      "生成結構化面試題庫、候選人溝通與跟進內容。",
      "Create an interview plan for this role with competencies to assess, sample questions, interviewer assignments, and follow-up email templates.",
      "請為此職位建立面試方案，包含要評估的能力、示例問題、面試官分工，以及跟進電郵範本。",
      ["Docs", "Gmail"],
      29,
      ["interview", "candidate", "questions", "follow-up"]
    ),
    makeCard(
      "hr-candidates",
      "hr",
      "Communicate with candidates",
      "與候選人溝通",
      "Draft candidate-facing messages that feel clear, timely, and respectful.",
      "撰寫清晰、及時且尊重候選人的溝通內容。",
      "Write candidate communication templates for interview invitations, timeline updates, and rejections that feel warm, direct, and brand-consistent.",
      "請撰寫候選人溝通範本，涵蓋面試邀請、流程更新與婉拒通知，語氣要溫暖、直接且符合品牌形象。",
      ["Gmail", "Docs"],
      29,
      ["candidate", "email", "recruiting", "templates"]
    ),
    makeCard(
      "hr-survey",
      "hr",
      "Conduct engagement and satisfaction surveys",
      "進行參與度與滿意度調查",
      "Design survey questions that surface usable signals instead of vague sentiment.",
      "設計能帶出可用訊號、而非空泛情緒的調查題目。",
      "Draft an employee survey with questions on engagement, communication, workload, and manager support, then suggest how to analyze the responses afterward.",
      "請起草一份員工調查，涵蓋投入感、溝通、工作量與主管支持，並建議後續如何分析結果。",
      ["Forms", "Sheets", "Docs"],
      30,
      ["survey", "engagement", "employee feedback", "analysis"]
    ),
    makeCard(
      "hr-learning",
      "hr",
      "Create personalized learning plans",
      "建立個人化學習計畫",
      "Translate role goals and skill gaps into realistic development steps.",
      "把職位目標與技能缺口轉成可行的發展步驟。",
      "Create a six-month learning plan for this employee based on role expectations, current strengths, growth areas, and available internal resources.",
      "請根據職位要求、現有優勢、成長空間與內部資源，為這位員工建立六個月學習計畫。",
      ["Docs", "Sheets"],
      30,
      ["learning plan", "development", "skills", "employee growth"]
    ),
    makeCard(
      "hr-onboard",
      "hr",
      "Onboard employees with clearer handoffs",
      "以更清晰的交接方式安排入職",
      "Keep onboarding coordinated across HR, manager, and new hire.",
      "讓 HR、主管與新員工之間的入職交接更順暢。",
      "Build an onboarding checklist that separates HR tasks, manager tasks, and employee tasks across the first two weeks.",
      "請建立一份入職清單，把首兩星期的 HR 任務、主管任務與員工任務分開列明。",
      ["Sheets", "Docs"],
      30,
      ["onboarding", "handoff", "checklist", "new hire"]
    ),
    makeCard(
      "hr-followup",
      "hr",
      "Summarize findings and draft follow-up surveys",
      "整理發現並起草後續調查",
      "Close the loop by turning survey results into next questions and actions.",
      "把調查結果轉成下一步問題與後續行動。",
      "Summarize the top findings from this employee survey, recommend follow-up actions, and draft a short pulse survey to validate whether the changes are helping.",
      "請整理這份員工調查的主要發現，建議後續行動，並起草一份短版脈搏調查，以驗證改變是否有效。",
      ["Docs", "Sheets"],
      31,
      ["follow-up survey", "findings", "pulse survey", "actions"]
    ),
    makeCard(
      "marketing-identity",
      "marketing",
      "Develop a visual identity brief",
      "建立視覺識別 brief",
      "Translate business positioning into art direction, color mood, and design cues.",
      "把品牌定位轉化成視覺方向、色彩情緒與設計線索。",
      "Create a visual identity brief for our brand, including personality, color direction, typography mood, visual references, and what the identity should avoid.",
      "請為品牌建立一份視覺識別 brief，包含品牌性格、色彩方向、字體氣質、視覺參考，以及應避免的風格。",
      ["Docs", "Slides"],
      32,
      ["brand", "identity", "visual", "creative brief"]
    ),
    makeCard(
      "marketing-brand-strategy",
      "marketing",
      "Shape a brand strategy",
      "制定品牌策略",
      "Clarify audience, positioning, proof points, and message pillars from source notes.",
      "根據資料釐清受眾、定位、佐證點與品牌信息支柱。",
      "Based on our customer notes and product strengths, draft a brand strategy outline with target audience, positioning statement, message pillars, and differentiation.",
      "請根據客戶筆記與產品優勢，起草一份品牌策略大綱，涵蓋目標受眾、定位語句、訊息支柱與差異化。",
      ["Docs", "Drive"],
      33,
      ["brand strategy", "positioning", "messaging", "audience"]
    ),
    makeCard(
      "marketing-partnerships",
      "marketing",
      "Brainstorm brand partnerships",
      "發想品牌合作夥伴",
      "Suggest partnership ideas that align with audience overlap and campaign goals.",
      "提出符合受眾重疊度與活動目標的合作想法。",
      "Suggest brand partnership ideas for our company, including why the fit makes sense, what each side gains, and one campaign concept for each match.",
      "請提出適合我們品牌的合作夥伴構想，說明合作合理性、雙方收益，以及每個合作的一個活動概念。",
      ["Docs"],
      33,
      ["partnership", "brand collaboration", "campaign", "audience overlap"]
    ),
    makeCard(
      "marketing-research",
      "marketing",
      "Conduct market research and identify trends",
      "進行市場研究並找出趨勢",
      "Turn broad market signals into focused content or campaign opportunities.",
      "把廣泛市場訊號整理成具體內容或活動機會。",
      "Review this market information and identify the strongest audience trends, whitespace opportunities, and campaign ideas worth testing first.",
      "請檢視這些市場資訊，找出最重要的受眾趨勢、空白機會，以及最值得優先測試的活動點子。",
      ["Gemini", "Docs"],
      34,
      ["market research", "trends", "opportunities", "campaign ideas"]
    ),
    makeCard(
      "marketing-content-distribution",
      "marketing",
      "Create content and distribution plans",
      "建立內容與分發計畫",
      "Pair message themes with formats, channels, and publishing cadence.",
      "把訊息主題與內容形式、渠道及發佈節奏配對。",
      "Build a content and distribution plan for this campaign with core themes, content formats, channel mix, publication timing, and success metrics.",
      "請為這個活動建立內容與分發計畫，包含主題、內容形式、渠道組合、發佈時間與成功指標。",
      ["Docs", "Sheets"],
      34,
      ["content plan", "distribution", "channels", "calendar"]
    ),
    makeCard(
      "marketing-collaboration",
      "marketing",
      "Improve collaboration with customers, agencies, and teams",
      "改善與客戶、代理商及團隊的協作",
      "Create shared briefs that reduce misalignment before creative work starts.",
      "在創意工作開始前，用共享 brief 減少認知落差。",
      "Draft a collaboration brief for our internal team and agency partner that defines the objective, deliverables, timeline, decision makers, and review process.",
      "請為內部團隊與代理商夥伴起草一份協作 brief，定義目標、交付物、時間表、決策者與審稿流程。",
      ["Docs"],
      34,
      ["collaboration", "agency", "brief", "alignment"]
    ),
    makeCard(
      "marketing-social-trends",
      "marketing",
      "Analyze social media trends",
      "分析社交媒體趨勢",
      "Turn noisy social data into a few strategic creative signals.",
      "把雜亂的社交數據整理成幾個有策略意義的創意訊號。",
      "Analyze these social media signals and summarize what topics are rising, what content styles are performing, and how our brand should respond.",
      "請分析這些社交媒體訊號，整理哪些主題正在上升、哪些內容形式表現較好，以及品牌應如何回應。",
      ["Sheets", "Docs"],
      35,
      ["social trends", "content performance", "audience", "response"]
    ),
    makeCard(
      "marketing-personas",
      "marketing",
      "Develop target audience personas",
      "建立目標受眾人物誌",
      "Convert qualitative notes into usable persona snapshots for content planning.",
      "把質性資料轉成內容規劃可用的人物誌。",
      "Create two target audience personas from this research, including demographics, motivations, objections, preferred channels, and purchase triggers.",
      "請根據這些研究建立兩個目標受眾人物誌，包含人口特徵、動機、疑慮、偏好渠道與購買觸發點。",
      ["Docs"],
      35,
      ["persona", "audience research", "motivations", "channels"]
    ),
    makeCard(
      "marketing-sem",
      "marketing",
      "Create and optimize SEM copy",
      "建立並優化 SEM 文案",
      "Draft ad copy variations that balance keywords, relevance, and CTR.",
      "生成兼顧關鍵字、相關性與點擊率的廣告文案。",
      "Generate search ad copy variations for this offer, including multiple headlines, descriptions, keyword intent coverage, and a short testing plan.",
      "請為這個優惠生成多個搜尋廣告版本，包含多組標題、描述、關鍵字意圖覆蓋，以及簡短測試計畫。",
      ["Docs", "Sheets"],
      36,
      ["SEM", "search ads", "copy", "testing"]
    ),
    makeCard(
      "marketing-acquisition",
      "marketing",
      "Draft customer acquisition communications",
      "起草客戶獲取溝通內容",
      "Shape a first-touch message that is persuasive without sounding generic.",
      "撰寫有說服力但不公式化的首次接觸內容。",
      "Draft an acquisition email sequence for this offer with a strong opening hook, proof points, objections handling, and one clear call to action per message.",
      "請為這個優惠建立一組獲客電郵序列，包含有力開場、佐證點、異議處理，以及每封一個清晰 CTA。",
      ["Gmail", "Docs"],
      36,
      ["acquisition", "email sequence", "CTA", "conversion"]
    ),
    makeCard(
      "marketing-inbound",
      "marketing",
      "Generate inbound campaign ideas",
      "生成 inbound 活動構想",
      "Connect audience pain points to content magnets and nurture steps.",
      "把受眾痛點連接到內容誘因與培育步驟。",
      "Suggest an inbound campaign for this audience, including a lead magnet, landing page angle, email nurture sequence, and simple success metrics.",
      "請為這個受眾提出一套 inbound 活動，包含 lead magnet、落地頁角度、電郵培育流程，以及簡單成功指標。",
      ["Docs"],
      37,
      ["inbound", "lead magnet", "landing page", "nurture"]
    ),
    makeCard(
      "marketing-personalized-content",
      "marketing",
      "Deliver personalized content at scale",
      "大規模提供個人化內容",
      "Define segments and message variations without losing consistency.",
      "在保持一致性的前提下定義分眾與訊息變體。",
      "Create a personalized content matrix for three audience segments, showing the message angle, proof points, CTA, and content format for each segment.",
      "請建立一個三個受眾分眾的個人化內容矩陣，列出各自的訊息角度、佐證點、CTA 與內容形式。",
      ["Sheets", "Docs"],
      37,
      ["personalization", "segments", "messaging", "matrix"]
    ),
    makeCard(
      "marketing-visuals",
      "marketing",
      "Create visuals for campaigns",
      "為活動建立視覺方向",
      "Turn campaign concepts into clear image or layout directions.",
      "把活動概念轉化成清楚的圖片或版面方向。",
      "Write a visual direction brief for this campaign, including image style, color mood, composition cues, text overlay guidance, and what the visuals must avoid.",
      "請為這個活動撰寫視覺方向 brief，包含圖片風格、色彩氛圍、構圖線索、文字疊加建議，以及必須避免的元素。",
      ["Slides", "Docs"],
      37,
      ["visuals", "campaign design", "brief", "art direction"]
    ),
    makeCard(
      "marketing-blog",
      "marketing",
      "Generate blog ideas",
      "生成 blog 題材",
      "Build a content backlog that aligns with search intent and brand voice.",
      "建立兼顧搜尋意圖與品牌語氣的內容題材庫。",
      "Suggest blog post ideas for this audience, grouped by beginner, mid-level, and decision-stage intent, with one core takeaway for each post.",
      "請為這個受眾提出 blog 題材，按初階、中階與決策階段意圖分組，並為每篇列出一個核心收穫。",
      ["Docs"],
      38,
      ["blog", "SEO", "content backlog", "search intent"]
    ),
    makeCard(
      "marketing-social",
      "marketing",
      "Create social media content",
      "生成社交媒體內容",
      "Draft platform-aware content ideas with consistent tone and CTA variations.",
      "按平台特性生成內容靈感，維持一致品牌語氣與不同 CTA 版本。",
      "Generate a week of social post ideas for this campaign, with a distinct angle for each post, a suggested CTA, and a tone that matches our brand voice.",
      "請為此活動生成一週社交帖文構思，每篇有不同切入角度、建議 CTA，並符合品牌語氣。",
      ["Docs"],
      38,
      ["social", "campaign", "content", "cta"]
    ),
    makeCard(
      "marketing-plan",
      "marketing",
      "Create a strategic marketing plan",
      "建立策略性市場計畫",
      "Connect business goals to audience targets, channels, budget, and measurement.",
      "把商業目標連接到受眾、渠道、預算與衡量方式。",
      "Draft a strategic marketing plan for the next quarter with goals, target segments, channel priorities, campaign themes, budget assumptions, and success metrics.",
      "請起草下一季度的策略性市場計畫，包含目標、受眾分群、渠道優先次序、活動主題、預算假設與成功指標。",
      ["Docs", "Sheets"],
      39,
      ["marketing plan", "quarterly", "budget", "metrics"]
    ),
    makeCard(
      "pm-uat",
      "pm",
      "Generate user acceptance tests",
      "生成用戶驗收測試",
      "Turn requirements into test scenarios, edge cases, and sign-off criteria.",
      "把需求轉化成測試場景、邊界情況與驗收標準。",
      "Based on these feature requirements, generate user acceptance test scenarios with expected outcomes, edge cases, and release sign-off criteria.",
      "請根據這份功能需求，生成用戶驗收測試場景，包含預期結果、邊界情況與上線簽核標準。",
      ["Docs", "Sheets"],
      40,
      ["uat", "testing", "requirements", "quality"]
    ),
    makeCard(
      "pm-status",
      "pm",
      "Write a project status update",
      "撰寫項目狀態更新",
      "Summarize progress, risks, decisions, and asks for stakeholders without noise.",
      "簡潔整理進度、風險、決策與需要支援的事項，避免資訊雜訊。",
      "Draft a weekly project update for stakeholders with accomplishments, risks, decisions needed, upcoming milestones, and any blockers requiring help.",
      "請起草一份每週項目更新給持份者，包含已完成事項、風險、待決策點、即將到來的里程碑，以及需要協助的阻礙。",
      ["Docs", "Gmail"],
      41,
      ["status", "stakeholders", "risks", "milestones"]
    ),
    makeCard(
      "pm-retro",
      "pm",
      "Run a project retrospective",
      "進行項目回顧",
      "Turn the end of a cycle into a useful team learning artifact.",
      "把一個周期的結束整理成對團隊有用的學習成果。",
      "Create a retrospective outline for this project that covers what went well, what slowed us down, what we learned, and the changes to apply next cycle.",
      "請為這個項目建立回顧大綱，涵蓋做得好的地方、拖慢進度的因素、學到的事，以及下個周期要採取的改變。",
      ["Docs"],
      41,
      ["retrospective", "lessons learned", "team", "improvement"]
    ),
    makeCard(
      "pm-issue-tracker",
      "pm",
      "Develop an issue tracker and communications",
      "建立問題追蹤與相關溝通",
      "Bring issue logging and stakeholder messaging into one working system.",
      "把問題追蹤與持份者溝通整理成同一套工作系統。",
      "Turn these project issues into a tracker with severity, owner, mitigation plan, external impact, and a stakeholder update summary.",
      "請把這些項目問題整理成追蹤表，包含嚴重程度、負責人、緩解方案、對外影響，以及持份者更新摘要。",
      ["Sheets", "Docs"],
      42,
      ["issue tracker", "mitigation", "stakeholder update", "severity"]
    ),
    makeCard(
      "pm-workback",
      "pm",
      "Create a workback schedule",
      "建立倒排工作計畫",
      "Start from a fixed launch date and derive milestones, dependencies, and owners.",
      "由固定推出日期反推所需里程碑、依賴關係與負責人。",
      "Build a workback schedule for this launch date, listing major milestones, dependencies, owners, review checkpoints, and risk flags.",
      "請為這個推出日期建立倒排工作計畫，列出主要里程碑、依賴關係、負責人、審核節點與風險提示。",
      ["Sheets", "Docs"],
      42,
      ["workback", "launch", "dependencies", "timeline"]
    ),
    makeCard(
      "sales-research",
      "sales",
      "Conduct account research",
      "進行客戶研究",
      "Prepare a quick profile with pain points, triggers, and likely value angles.",
      "快速整理客戶背景、痛點、觸發因素與可能的價值切入點。",
      "Create an account research brief on this prospect, including business priorities, possible pain points, likely buying triggers, and a tailored outreach angle.",
      "請建立這位潛在客戶的研究摘要，包含業務重點、可能痛點、購買觸發點，以及客製化接觸角度。",
      ["Docs", "Gemini"],
      43,
      ["prospect", "account research", "pain points", "outreach"]
    ),
    makeCard(
      "sales-journey",
      "sales",
      "Map customer journeys",
      "繪製客戶旅程",
      "Show where buyers hesitate, what they need, and how the team should respond.",
      "顯示買家在哪些節點猶豫、需要甚麼，以及團隊應如何回應。",
      "Map the customer journey for this account type from awareness to purchase, including needs, friction points, objections, and the best supporting asset at each stage.",
      "請為這類客戶繪製從認知到購買的客戶旅程，列出需求、阻力、異議，以及每個階段最適合的支援素材。",
      ["Docs", "Slides"],
      44,
      ["customer journey", "funnel", "objections", "sales enablement"]
    ),
    makeCard(
      "sales-rfp",
      "sales",
      "Support the RFP process",
      "支援 RFP 提案流程",
      "Organize requirements, response themes, and gaps before the team drafts the proposal.",
      "在正式撰寫提案前，先整理需求、回應主題與缺口。",
      "Review this RFP and summarize key requirements, evaluation criteria, response themes, missing inputs, and the best way to structure our reply.",
      "請審閱這份 RFP，整理出關鍵需求、評分標準、回應主軸、缺少資訊，以及最合適的回覆結構。",
      ["Docs", "Drive"],
      45,
      ["rfp", "proposal", "requirements", "structure"]
    ),
    makeCard(
      "sales-mobile",
      "sales",
      "Access information and tools on your phone",
      "在手機上快速取得資訊與工具",
      "Prepare concise mobile-ready notes for meetings or outreach while moving.",
      "在移動中準備可於手機快速閱讀的會議或外聯筆記。",
      "Condense this customer account into a mobile-ready briefing with key facts, last interaction, open opportunity, and the best next move.",
      "請把這個客戶帳戶整理成適合手機閱讀的簡報，包含關鍵資訊、上次互動、開放中的機會，以及最佳下一步。",
      ["Docs", "Gmail"],
      45,
      ["mobile", "account brief", "on the go", "sales"]
    ),
    makeCard(
      "sales-relationships",
      "sales",
      "Develop customer relationships",
      "建立客戶關係",
      "Use small, useful touchpoints instead of generic follow-up.",
      "以小而有用的接觸點代替制式跟進。",
      "Suggest relationship-building follow-up ideas for this customer based on their industry, recent interaction, and likely priorities over the next quarter.",
      "請根據客戶所屬行業、最近互動與下一季度可能優先事項，提出建立關係的跟進方式。",
      ["Gmail", "Docs"],
      45,
      ["relationship building", "follow-up", "customer", "industry"]
    ),
    makeCard(
      "sales-team-support",
      "sales",
      "Support the sales team",
      "支援銷售團隊",
      "Create reusable support materials that reduce prep time for reps.",
      "建立可重複使用的支援材料，降低業務準備時間。",
      "Create a sales support brief that gives reps the core messaging, objection handling, proof points, and discovery questions for this offer.",
      "請建立一份銷售支援 brief，提供業務這個方案的核心訊息、異議處理、佐證點與探索問題。",
      ["Docs"],
      46,
      ["sales enablement", "objections", "proof points", "brief"]
    ),
    makeCard(
      "sales-coaching",
      "sales",
      "Coach and train the sales team",
      "訓練與指導銷售團隊",
      "Turn sales patterns into practical coaching prompts and role-play ideas.",
      "把銷售模式整理成實用的 coaching 提示與角色扮演題目。",
      "Review these recent sales calls and identify coaching themes, skill gaps, practice exercises, and one role-play scenario for the team.",
      "請檢視這些近期銷售通話，找出 coaching 主題、能力缺口、練習方式，以及一個適合團隊的角色扮演情境。",
      ["Docs", "Meet"],
      46,
      ["sales coaching", "role play", "skills", "training"]
    ),
    makeCard(
      "sales-custom-asset",
      "sales",
      "Customize assets for a specific customer",
      "為特定客戶客製素材",
      "Tailor value stories around the pain points already mentioned by the buyer.",
      "針對買家已提出的痛點，客製化價值敘事。",
      "Draft a customer-specific one-pager showing how our product solves the pain points already mentioned in this account, with proof points and a clear next step.",
      "請起草一份客製化一頁簡介，說明我們的產品如何解決此客戶已提過的痛點，加入佐證點與清晰下一步。",
      ["Docs", "Slides"],
      47,
      ["custom asset", "pain points", "one pager", "customer-specific"]
    ),
    makeCard(
      "sales-calls",
      "sales",
      "Prepare for a new customer call",
      "準備新客戶會議",
      "Shape a discovery call around context, trust-building, and next-step momentum.",
      "把首次探索會議設計成兼顧背景理解、建立信任與推進下一步。",
      "Prepare a 30-minute discovery call plan for this prospect with opening questions, business hypothesis, credibility points, and a suggested next-step close.",
      "請為這位潛在客戶準備一個 30 分鐘探索會議方案，包含開場問題、業務假設、可信度亮點與建議收尾。",
      ["Docs", "Meet"],
      48,
      ["discovery call", "sales", "questions", "prospect"]
    ),
    makeCard(
      "sales-outreach",
      "sales",
      "Personalize outreach at scale",
      "大規模個人化外聯",
      "Keep outreach relevant even when building repeatable templates.",
      "即使用範本，也要讓外聯內容保持相關性。",
      "Create a reusable outreach template with placeholders for industry context, recent trigger event, business value, and a low-friction call to action.",
      "請建立一個可重複使用的外聯範本，預留行業背景、近期觸發事件、商業價值，以及低門檻 CTA 的欄位。",
      ["Gmail", "Docs"],
      49,
      ["outreach", "template", "personalization", "CTA"]
    ),
    makeCard(
      "sales-appreciation",
      "sales",
      "Create customer appreciation materials",
      "建立客戶感謝素材",
      "Make appreciation feel thoughtful instead of transactional.",
      "讓感謝內容更有心，而不是只是交易性的跟進。",
      "Write a customer appreciation message pack with one short email, one handwritten-note style version, and one event follow-up version.",
      "請撰寫一組客戶感謝訊息，包含一封短電郵、一個手寫卡片風格版本，以及一個活動後跟進版本。",
      ["Docs", "Gmail"],
      49,
      ["appreciation", "thank you", "customer relationship", "follow-up"]
    ),
    makeCard(
      "smallbiz-pricing",
      "small-business",
      "Create pricing comparisons",
      "建立價格比較",
      "Compare packages, tradeoffs, and value propositions in a customer-friendly way.",
      "用客戶容易理解的方式比較方案、取捨與價值差異。",
      "Compare these three pricing options in a table with features, tradeoffs, ideal customer type, and a recommendation for budget-conscious buyers.",
      "請以表格比較這三個價格方案，包含功能、取捨、適合客群，以及對預算敏感買家的建議。",
      ["Sheets", "Docs"],
      50,
      ["pricing", "comparison", "table", "budget"]
    ),
    makeCard(
      "smallbiz-productivity",
      "small-business",
      "Enhance personal productivity",
      "提升個人生產力",
      "Build practical routines for owners who switch between many roles.",
      "為身兼多職的小企業主建立實用工作節奏。",
      "Review this list of business tasks and turn it into a practical weekly operating plan with priorities, batching ideas, and what to defer.",
      "請檢視這份業務任務清單，把它整理成一個實際可行的每週工作計畫，包含優先級、可批次處理的工作，以及可延後事項。",
      ["Docs", "Sheets"],
      51,
      ["productivity", "owner", "weekly plan", "priorities"]
    ),
    makeCard(
      "smallbiz-marketing",
      "small-business",
      "Brainstorm lightweight marketing ideas",
      "發想輕量營銷內容",
      "Generate practical content ideas that fit small teams with limited time and budget.",
      "生成適合小團隊、低時間與低預算情境的實用營銷內容。",
      "Suggest simple marketing ideas we can execute this month with a small team, limited budget, and a need for fast customer visibility.",
      "請建議一些本月可執行的簡單營銷點子，前提是團隊小、預算有限，而且需要快速提升曝光。",
      ["Docs", "Gemini"],
      51,
      ["small team", "marketing", "budget", "ideas"]
    ),
    makeCard(
      "smallbiz-competitive",
      "small-business",
      "Develop a competitive analysis",
      "建立競爭分析",
      "Compare nearby or direct alternatives in a way that informs positioning choices.",
      "以有助定位決策的方式比較附近或直接競爭者。",
      "Build a competitive analysis for our business that compares pricing, offer clarity, positioning, customer experience, and easy moves we could test this quarter.",
      "請為我們的業務建立競爭分析，比較價格、方案清晰度、定位、客戶體驗，以及本季可測試的簡單改進。",
      ["Docs", "Sheets"],
      52,
      ["competitive analysis", "small business", "positioning", "pricing"]
    ),
    makeCard(
      "smallbiz-fundraising",
      "small-business",
      "Support fundraising and investor relations",
      "支援募資與投資者關係",
      "Turn business progress into a sharper narrative for investors or supporters.",
      "把業務進展整理成更清晰的投資者敘事。",
      "Draft an investor update covering progress, traction, current focus, challenges, and the specific support or follow-up we want from backers.",
      "請起草一份投資者更新，說明進展、成長訊號、目前重點、挑戰，以及我們希望投資者提供的具體支援。",
      ["Docs", "Gmail"],
      52,
      ["investor update", "fundraising", "traction", "support"]
    ),
    makeCard(
      "smallbiz-timeoff",
      "small-business",
      "Manage time-off policies and tracking",
      "管理休假政策與追蹤",
      "Make leave rules easier for a small team to understand and follow.",
      "讓小團隊更容易理解與遵守休假規則。",
      "Create a simple time-off policy summary and tracker that explains the rules, approval process, blackout periods, and current balances for the team.",
      "請建立一份簡單的休假政策摘要與追蹤表，說明規則、批准流程、限制時段，以及團隊現有餘額。",
      ["Docs", "Sheets"],
      53,
      ["time off", "policy", "tracker", "small team"]
    ),
    makeCard(
      "startup-strategy",
      "startup",
      "Brainstorm business and strategy options",
      "構思商業與策略選項",
      "Explore multiple strategic directions with assumptions, upside, and risk.",
      "從多個方向思考策略，並標示假設、潛在收益與風險。",
      "Generate three strategic paths for our startup over the next 12 months. For each path, explain the core assumption, upside, downside, and what we would need to validate first.",
      "請為我們的初創公司提出未來 12 個月的三條策略路徑，並分別說明核心假設、潛在收益、風險，以及最先要驗證的事項。",
      ["Gemini", "Docs"],
      54,
      ["startup", "strategy", "options", "validation"]
    ),
    makeCard(
      "startup-pitch",
      "startup",
      "Develop an elevator pitch",
      "撰寫電梯簡報",
      "Condense the company story into a short, memorable, investor-ready narrative.",
      "把公司故事壓縮成短而有記憶點、適合投資人聽的敘事。",
      "Write an elevator pitch for our startup that explains the problem, the product, the market opportunity, and why now in under 60 seconds.",
      "請為我們的初創公司撰寫一段電梯簡報，在 60 秒內說清楚問題、產品、市場機會，以及為何是現在。",
      ["Docs"],
      55,
      ["pitch", "investor", "story", "startup"]
    ),
    makeCard(
      "startup-personal-brand",
      "startup",
      "Develop your personal brand",
      "建立個人品牌",
      "Shape how a founder shows up across bios, posts, and speaking opportunities.",
      "整理創辦人在個人簡介、貼文與公開場合中的對外形象。",
      "Create a founder personal brand brief covering point of view, topics to own, tone, credibility signals, and content formats to use consistently.",
      "請建立一份創辦人個人品牌 brief，涵蓋核心觀點、適合主導的主題、語氣、可信度訊號，以及應持續使用的內容形式。",
      ["Docs"],
      55,
      ["personal brand", "founder", "positioning", "content"]
    ),
    makeCard(
      "startup-vendors",
      "startup",
      "Communicate and negotiate with vendors",
      "與供應商溝通及談判",
      "Prepare sharper vendor conversations with clearer targets and fallback positions.",
      "以更清楚的目標與備案，準備供應商溝通。",
      "Draft a vendor negotiation brief with our target terms, fallback options, leverage points, budget ceiling, and the questions we need answered before committing.",
      "請起草一份供應商談判 brief，包含目標條款、備案、談判籌碼、預算上限，以及承諾前必須問清楚的問題。",
      ["Docs", "Sheets"],
      56,
      ["vendor negotiation", "terms", "budget", "fallback"]
    ),
    makeCard(
      "startup-budget",
      "startup",
      "Plan and track budgets",
      "規劃與追蹤預算",
      "Translate ambition into spend visibility and decision boundaries.",
      "把野心轉化成可見的支出狀況與決策邊界。",
      "Build a startup budget tracker with monthly spend categories, runway assumptions, planned versus actual spend, and thresholds that should trigger a review.",
      "請建立一個初創公司預算追蹤表，包含每月支出分類、runway 假設、計畫與實際支出，以及需要觸發檢討的門檻。",
      ["Sheets"],
      56,
      ["budget", "runway", "spend tracker", "review threshold"]
    ),
    makeCard(
      "startup-launch",
      "startup",
      "Build a product launch plan",
      "建立產品上市計畫",
      "Map launch goals, channels, milestones, owners, and post-launch checks.",
      "整理產品上市目標、渠道、里程碑、負責人與上線後檢查點。",
      "Create a product launch plan that includes goals, target audience, launch channels, internal dependencies, success metrics, and a first-week follow-up checklist.",
      "請建立一份產品上市計畫，包含目標、目標受眾、推出渠道、內部依賴項、成功指標，以及首週跟進清單。",
      ["Docs", "Sheets"],
      57,
      ["launch", "product", "metrics", "checklist"]
    ),
    makeCard(
      "startup-roadmap",
      "startup",
      "Develop product strategy and roadmap",
      "制定產品策略與路線圖",
      "Turn market direction and product bets into a prioritized roadmap story.",
      "把市場方向與產品賭注整理成有優先次序的路線圖敘事。",
      "Draft a product strategy and roadmap outline for the next two quarters, including user problems, strategic bets, priorities, risks, and what not to build yet.",
      "請為未來兩個季度起草一份產品策略與路線圖大綱，包含用戶問題、策略性賭注、優先事項、風險，以及暫時不應投入的方向。",
      ["Docs", "Slides"],
      57,
      ["roadmap", "product strategy", "priorities", "risks"]
    ),
  ],
};
